LOCAL_PATH := device/bird/ct07

# Stock blobs (vendor/ctyon/ct07, generated by extract-files.sh)
$(call inherit-product, vendor/ctyon/ct07/ct07-vendor.mk)

# Ramdisk
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/rootdir/fstab.mt6735:root/fstab.mt6735 \
    $(LOCAL_PATH)/rootdir/init.mt6735.rc:root/init.mt6735.rc \
    $(LOCAL_PATH)/rootdir/init.project.rc:root/init.project.rc \
    $(LOCAL_PATH)/rootdir/init.modem.rc:root/init.modem.rc \
    $(LOCAL_PATH)/rootdir/init.c2k.rc:root/init.c2k.rc \
    $(LOCAL_PATH)/rootdir/init.mt6735.usb.rc:root/init.mt6735.usb.rc \
    $(LOCAL_PATH)/rootdir/ueventd.mt6735.rc:root/ueventd.mt6735.rc

# USB: MTP and adb. WITH_ADB_INSECURE=true turns adb authorization off, as
# in LineageOS 15.1 and later. The first value of a key wins in default.prop,
# and vendor/cm adds ro.adb.secure=1.
ifeq ($(WITH_ADB_INSECURE),true)
ADDITIONAL_DEFAULT_PROPERTIES := \
    ro.adb.secure=0 \
    $(filter-out ro.adb.secure=1,$(ADDITIONAL_DEFAULT_PROPERTIES))
endif
ADDITIONAL_DEFAULT_PROPERTIES += \
    persist.sys.usb.config=mtp,adb
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
    frameworks/native/data/etc/android.hardware.usb.host.xml:system/etc/permissions/android.hardware.usb.host.xml
PRODUCT_PACKAGES += \
    com.android.future.usb.accessory

# Permissions. No android.hardware.touchscreen: without a touchscreen
# declared, the framework runs in non-touch (D-pad) mode.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/permissions/ct07_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
    frameworks/native/data/etc/android.hardware.faketouch.xml:system/etc/permissions/android.hardware.faketouch.xml \
    frameworks/native/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
    frameworks/native/data/etc/android.hardware.bluetooth.xml:system/etc/permissions/android.hardware.bluetooth.xml \
    frameworks/native/data/etc/android.hardware.bluetooth_le.xml:system/etc/permissions/android.hardware.bluetooth_le.xml \
    frameworks/native/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
    frameworks/native/data/etc/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
    frameworks/native/data/etc/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml

PRODUCT_CHARACTERISTICS := default

PRODUCT_PROPERTY_OVERRIDES += \
    ro.board.platform=mt6737t \
    ro.mediatek.platform=MT6737T \
    ro.mediatek.project.path=device/bird/bd6737t_35g_a_m0

# WebView is left out: no room for it on a 512 MB phone.
PRODUCT_PACKAGES := $(filter-out webview,$(PRODUCT_PACKAGES))

# Dex pre-optimization on the build host
WITH_DEXPREOPT := true
WITH_DEXPREOPT_PIC := true

DEVICE_PACKAGE_OVERLAYS += $(LOCAL_PATH)/overlay

# Keypad
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl

# Keypad apps: MonoLaunch (home), Traditional T9 (input method) and the key
# mouse (D-pad pointer, CT07_WITH_KEYMOUSE=false leaves it out).
PRODUCT_PACKAGES += \
    MonoLaunch \
    TraditionalT9
ifneq ($(CT07_WITH_KEYMOUSE),false)
PRODUCT_PACKAGES += CT07KeyMouse
PRODUCT_PROPERTY_OVERRIDES += ro.bdfun.uinput_mouse=true
endif

# Memory: zram swap after boot
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/init/ct07-lowram.rc:system/etc/init/ct07-lowram.rc

# Locale
PRODUCT_PROPERTY_OVERRIDES += \
    persist.sys.locale=ru-RU \
    persist.sys.timezone=Europe/Moscow

# Wi-Fi
PRODUCT_PACKAGES += \
    wpa_supplicant \
    wpa_supplicant.conf \
    hostapd \
    wpa_cli \
    hostapd_cli \
    libwpa_client \
    lib_driver_cmd_mt66xx

# Bluetooth: btaddr_mtk exports the NVRAM address for the stack.
PRODUCT_PACKAGES += \
    btaddr_mtk \
    btaddr_settings.sh
PRODUCT_PROPERTY_OVERRIDES += \
    ro.bt.bdaddr_path=/data/misc/bluetooth/bdaddr

# Media
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/media_profiles.xml:system/etc/media_profiles.xml \
    frameworks/av/media/libstagefright/data/media_codecs_google_audio.xml:system/etc/media_codecs_google_audio.xml \
    frameworks/av/media/libstagefright/data/media_codecs_google_video_le.xml:system/etc/media_codecs_google_video_le.xml

# FM radio
PRODUCT_PACKAGES += \
    FMRadio \
    libfmjni
PRODUCT_PROPERTY_OVERRIDES += \
    ro.mtk_fm_short_antenna_support=true

# Shims for stock blobs (see BoardConfig.mk)
PRODUCT_PACKAGES += \
    libmtk_agpsd_shim \
    libshim_ct07_audio

# Off-mode charging (healthd charger mode)
PRODUCT_PACKAGES += \
    charger_res_images

# Telephony: stock mtk-ril.so with the MT6735 RIL class (ril/), dual SIM.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.telephony.ril_class=MT6735 \
    persist.radio.multisim.config=dsds \
    ro.telephony.sim.count=2 \
    persist.gemini.sim_num=2 \
    ril.current.share_modem=2 \
    ro.mtk_enable_md1=1 \
    ro.mtk_md_sbp_custom_value=0 \
    persist.radio.mtk_dsbp_support=1 \
    persist.radio.default.sim=0 \
    persist.radio.mobile.data=0,0 \
    persist.radio.fd.counter=15 \
    persist.radio.fd.off.counter=5 \
    persist.radio.fd.r8.counter=15 \
    persist.radio.fd.off.r8.counter=5 \
    ril.external.md=0 \
    ril.telephony.mode=0 \
    ro.telephony.default_network=9,0 \
    ro.logd.size.radio=256K
