LOCAL_PATH := device/bird/ct07

# Stock blobs (vendor/ctyon/ct07, generated by extract-files.sh)
$(call inherit-product, vendor/ctyon/ct07/ct07-vendor.mk)

# Screen: 240x320, ldpi
PRODUCT_AAPT_CONFIG := normal ldpi
PRODUCT_AAPT_PREF_CONFIG := ldpi
PRODUCT_CHARACTERISTICS := default

# Ramdisk
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/rootdir/fstab.mt6735:root/fstab.mt6735 \
    $(LOCAL_PATH)/rootdir/init.mt6735.rc:root/init.mt6735.rc \
    $(LOCAL_PATH)/rootdir/init.project.rc:root/init.project.rc \
    $(LOCAL_PATH)/rootdir/init.modem.rc:root/init.modem.rc \
    $(LOCAL_PATH)/rootdir/init.mt6735.usb.rc:root/init.mt6735.usb.rc \
    $(LOCAL_PATH)/rootdir/init.ct07.rc:root/init.ct07.rc \
    $(LOCAL_PATH)/rootdir/ueventd.mt6735.rc:root/ueventd.mt6735.rc \
    $(LOCAL_PATH)/rootdir/recovery.fstab:recovery/root/fstab.mt6735

# USB: MTP and adb; adbd uses FunctionFS on the legacy android_usb gadget.
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
    persist.sys.usb.config=mtp,adb \
    sys.usb.ffs.aio_compat=1

# Permissions. No android.hardware.touchscreen: without a touchscreen
# declared, the framework runs in non-touch (D-pad) mode.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/permissions/ct07_core_hardware.xml:system/etc/permissions/handheld_core_hardware.xml \
    $(LOCAL_PATH)/permissions/privapp-permissions-ct07.xml:system/etc/permissions/privapp-permissions-ct07.xml \
    frameworks/native/data/etc/android.hardware.faketouch.xml:system/etc/permissions/android.hardware.faketouch.xml \
    frameworks/native/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
    frameworks/native/data/etc/android.hardware.bluetooth.xml:system/etc/permissions/android.hardware.bluetooth.xml \
    frameworks/native/data/etc/android.hardware.bluetooth_le.xml:system/etc/permissions/android.hardware.bluetooth_le.xml \
    frameworks/native/data/etc/android.hardware.telephony.gsm.xml:system/etc/permissions/android.hardware.telephony.gsm.xml \
    frameworks/native/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
    frameworks/native/data/etc/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
    frameworks/native/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml

# Keypad
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/keylayout/mtk-kpd.kl:system/usr/keylayout/mtk-kpd.kl

# Keypad apps: MonoLaunch (home), Traditional T9 (input method) and the key
# mouse (D-pad pointer, CT07_WITH_KEYMOUSE=false leaves it out).
PRODUCT_PACKAGES += \
    MonoLaunch \
    TraditionalT9
ifneq ($(CT07_WITH_KEYMOUSE),false)
PRODUCT_PACKAGES += CT07KeyMouse
PRODUCT_PROPERTY_OVERRIDES += ro.bdfun.uinput_mouse=true
endif

# Base apps this phone does not ship (prebuilt/Android.mk)
PRODUCT_PACKAGES += RemovePackages

DEVICE_PACKAGE_OVERLAYS += $(LOCAL_PATH)/overlay

# Memory: zram swap after boot
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/init/ct07-lowram.rc:system/etc/init/ct07-lowram.rc

# Locale
PRODUCT_PROPERTY_OVERRIDES += \
    persist.sys.locale=ru-RU \
    persist.sys.timezone=Europe/Moscow

# HIDL: the AOSP default implementations around the stock legacy modules.
# No sensors HAL: the stock module is API 1.0, which sensors@1.0-impl
# rejects, and the accelerometer does not respond on I2C.
PRODUCT_PACKAGES += \
    android.hardware.graphics.composer@2.1-impl \
    android.hardware.graphics.composer@2.1-service \
    android.hardware.graphics.allocator@2.0-impl \
    android.hardware.graphics.allocator@2.0-service \
    android.hardware.graphics.mapper@2.0-impl \
    libhwc2on1adapter \
    android.hardware.keymaster@3.0-impl \
    android.hardware.keymaster@3.0-service \
    android.hardware.audio@2.0-impl \
    android.hardware.audio@2.0-service \
    android.hardware.audio.effect@2.0-impl \
    android.hardware.bluetooth@1.0-impl \
    android.hardware.bluetooth@1.0-service \
    android.hardware.camera.provider@2.4-impl \
    android.hardware.camera.provider@2.4-service \
    android.hardware.light@2.0-impl \
    android.hardware.light@2.0-service \
    android.hardware.vibrator@1.0-impl \
    android.hardware.vibrator@1.0-service \
    android.hardware.gnss@1.0-impl \
    android.hardware.drm@1.0-impl \
    android.hardware.drm@1.0-service

# GNSS runs passthrough inside system_server (no gnss@1.0-service): the
# legacy module is not safe to keep alive across system_server restarts.

# Bluetooth: btaddr_mtk exports the NVRAM address for the HAL.
PRODUCT_PACKAGES += btaddr_mtk
PRODUCT_PROPERTY_OVERRIDES += \
    ro.bt.bdaddr_path=/data/misc/bluetooth/bdaddr

# Audio
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/init/ct07-audio-c2k.rc:system/etc/init/ct07-audio-c2k.rc
PRODUCT_PACKAGES += \
    audio.a2dp.default \
    audio.usb.default \
    audio.r_submix.default

# Media
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/configs/media_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    frameworks/av/media/libstagefright/data/media_codecs_google_audio.xml:system/etc/media_codecs_google_audio.xml \
    frameworks/av/media/libstagefright/data/media_codecs_google_video_le.xml:system/etc/media_codecs_google_video_le.xml

# Syscalls the stock MTK OMX components need in mediacodec.
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/seccomp/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy

# Camera: Snap uses the Camera1 API the HAL1 camera module provides.
PRODUCT_PACKAGES += Snap

# FM radio
PRODUCT_PACKAGES += \
    FMRadio \
    libfmjni
PRODUCT_PROPERTY_OVERRIDES += \
    ro.mtk_fm_short_antenna_support=true
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/permissions/ct07-fm-radio.xml:system/etc/permissions/ct07-fm-radio.xml

# Wi-Fi
PRODUCT_PACKAGES += \
    android.hardware.wifi@1.0-service \
    wificond \
    wpa_supplicant \
    wpa_supplicant.conf \
    hostapd \
    lib_driver_cmd_mt66xx \
    libwpa_client \
    libwifi-hal-mt66xx
PRODUCT_COPY_FILES += \
    external/wpa_supplicant_8/wpa_supplicant/wpa_supplicant_template.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf

# Telephony: MTK HIDL rild and libril (vendor/mediatek/ril) with the stock
# mtk-ril.so.
ENABLE_VENDOR_RIL_SERVICE := true
PRODUCT_PACKAGES += \
    rild \
    libril
PRODUCT_PROPERTY_OVERRIDES += \
    rild.libpath=mtk-ril.so \
    persist.radio.multisim.config=dsds \
    ro.telephony.sim.count=2 \
    persist.gemini.sim_num=2 \
    ril.current.share_modem=2 \
    ro.mtk_enable_md1=1 \
    ro.telephony.default_network=9,0 \
    ro.logd.size.radio=256K

# Shims for the stock blobs (see board/shims.mk)
PRODUCT_PACKAGES += \
    libmtkshim_gui \
    libmtkshim_ui \
    libshim_ct07 \
    libshim_ct07_icu

# gps.mt6737t.so needs libcurl.
PRODUCT_PACKAGES += libcurl

# Display and memory
PRODUCT_PROPERTY_OVERRIDES += \
    ro.sf.lcd_density=120 \
    ro.opengles.version=196608 \
    ro.hardware.egl=mali \
    ro.config.max_starting_bg=4
